### ISSUE TITLE
Android Basics: Lemonade app

### ISSUE THREAD

**Issue by harr1424** [google-developer-training/android-basics-kotlin-lemonade-app#22]
On Page 5 Step 2: Implement clickLemonImage(), the instructions for sub-step 2 are ambiguous: 

> SQUEEZE: Increment the squeezeCount by 1 and decrement the lemonSize by 1. **_Remember that a lemon will require a variable number of squeezes before the squeezeCount_**. Transition to the DRINK state only if the new lemonSize is equal to 0. Otherwise, the app should remain in the SQUEEZE state.

Should this read "Remember that a lemon will require a variable number of squeezes before changing to a "drink" state?

**Comment by osuleymanova** [comment]
@harr1424 
Thank you for reaching out to us. The issue is fixed and will be published soon.
