### ISSUE TITLE
Android Basics: Lemonade app

### ISSUE THREAD

**Issue by RKBambi** [google-developer-training/android-basics-kotlin-lemonade-app#24]
So I'm running the latest version of Android Studios and after downloading this source code and opening it as a new project, I can't even begin to start working on it because it has 148 errors. Is this intentional? Am I supposed to figure out how to resolve all 148 errors before I even begin the project? I'm having some real difficulties with this one, but maybe I did something fundamentally wrong that screwed it up from the beginning. If anyone could help, that would be awesome.

**Comment by brrcd** [comment]
Hello, can you show those errors?

**Comment by RKBambi** [comment]
These are the problems that came up when I opened the file that I downloaded on GitHub. It may be an easy solution, but it's a little overwhelming
![problems1](https://user-images.githubuserc
![problems 2](https://user-images.githubusercontent.com/96
![problems3](https://user-images.githubusercontent.com/96219375/146687529-e1060134-f2b9-4748-943e-05c23023c7ce.png)
![problems4](https://user-images.githubusercontent.com/96219375/146687532-9e3096d3-147c-451a-b85c-ab52daa8a32d.png)

219375/146687524-37eda4c6-3034-4c83-960a-f90db2337318.png)
ontent.com/96219375/146687522-e2d4d192-fcda-4207-b152-9ab9cafa277d.png)
.

**Comment by brrcd** [comment]
Looks like you made mistake on one of the steps. May be android studio set up wrong.

**Comment by RKBambi** [comment]
Could you give any more clarification on that? What step in the setup would
be causing this? To my knowledge, I followed the set up exactly as it was
described in the lesson, but the version I'm using now is different from
the version from when this was created. Any tips or insight that you could
give me?

**Comment by brrcd** [comment]
I tried myself and my app is working fine. The way i did is :

1. Open android studio;
2. Press "Get from VSC" that means get code from version control system (github);
3. Copied and pasted " https://github.com/google-developer-training/android-basics-kotlin-lemonade-app ";
4. Wait till download/sync complete;
5. Continue with your unit.

![image](https://user-images.githubusercontent.com/29070360/147341360-52d54985-fb81-45d8-9308-b121c7af4bff.png)

**Comment by RKBambi** [comment]
That makes a little sense. So does that mean I do not download the file
from github, unzip and open that file? Instead there is a direct way to
open files using the version they were meant to run on? I apologize as I've
only taken a handful of classes for Java and C++ so android studio is
completely new to me. I think it's brilliant in the way that it simplifies
coding, but some of these tasks are driving me bonkers.
If I'm interpreting this correctly then where is the option for "get from
VSC"? Is it just under the file options menu? I'm away from my computer
right now so I can't check the different menu options? Would you be willing
to lead me through it?

**Comment by brrcd** [comment]
> So does that mean I do not download the file from github, unzip and open that file?

Didnt tried this one, the way i using is easier.

> If I'm interpreting this correctly then where is the option for "get from VSC"?

First option you get when you starting android studio:
![image](https://user-images.githubusercontent.com/29070360/147342648-c990189e-1927-42eb-81f4-03b0598a4eb0.png)

Second one you get when some project already opened:
![image](https://user-images.githubusercontent.com/29070360/147342721-93b9513f-00b1-4f08-ab4f-fec6c06e1e95.png)

**Comment by RKBambi** [comment]
Holy cow. So that actually worked! It is now running with no errors
whatsoever. That's very different from the instructions given on
the website. I'm not sure why they have such outdated information on their
site. Do better Google.
Thank you so much. I have some other problems I'm running into if you have
time. Primarily the emulator that they had me set up in the beginning wont
run any of the apps that they're training me to create. This wasn't a
problem at first because they taught me how to turn on developer mode on my
phone so I was able to just run the apps on my phone. However, now when I
plug my phone into my pc it says that it doesn't recognize the device.
So although the program runs with no errors now, the emulator does not work
and I can't use my phone. So I need to figure out either why the emulator
isn't working or why the phone is no longer recognized when I plug it in.
By any chance have you run into this before? Any quick fixes that I can use
to solve this problem?

**Comment by brrcd** [comment]
How much RAM does ur pc have? Does emulator launching, can u navigate inside of it? Im using stationary pc with 16 gigs of RAM, having no issues with running emulator. But my laptop with 8 gigs is struggling to launch it so i use physycal device to test apps with it.

**Comment by RKBambi** [comment]
My system says 12gb of ram so probably 16 with 4 being used. The emulator
launches, but no longer goes past the original save state of the first
program I ever ran that just says "hello world". It refuses to load in any
new programs.

**Comment by Yugal41735** [comment]
In my case it is taking a lot of time in syncing. So is there any way to shorten that time ?
