### ISSUE TITLE
Android Basics: Lemonade app

### ISSUE THREAD

**Issue by digitalSalt** [google-developer-training/android-basics-kotlin-lemonade-app#3]
Hi! 

I am following the android basics with Kotlin course, and noticed a possible typo in the Testing section for the Lemonade App. I believe the test case referred to in the screen shot is show near the end of the page (step 7). 

![image](https://user-images.githubusercontent.com/20101536/128120615-ea8cbd70-5706-4396-a04a-013b24f3eb89.png)

Thank you for creating the course content 😃

**Comment by osuleymanova** [comment]
@digitalSalt 
Thank you for reaching out to us. This typo is fixed and will be published soon.
