### ISSUE TITLE
Android Basics: Lemonade app

### ISSUE THREAD

**Issue by idongesit98** [google-developer-training/android-basics-kotlin-lemonade-app#30]
i keep getting a null pointer exception in my code
![null pointer exception error](https://user-images.githubusercontent.com/101020121/156898703-62b0ef62-13d2-45ce-8e12-11b495e9f3f1.png)

**Comment by CosmicCandi** [comment]
So, fundamentally, Null Pointers happen when the object you're trying to call a method on, is null.
Check to see if the view you're calling the onClickListener for has been initialized. One of the previous modules talked about getting an NPE if you tried calling your setContentView before initializing it. Also looking through the project briefly, it looks like `lemonImage: ImageView?` is initialized as null. Check these places to see if you can trace down your NPE. Once you're sure you have an object there, things should be working properly.
