### ISSUE TITLE
Android Basics: Lemonade app

### ISSUE THREAD

**Issue by jhoh10** [google-developer-training/android-basics-kotlin-lemonade-app#38]
With the latest version of Android studio, this lemonade app doesn't open the unzipped lemonade code directory properly. This is what the Android project view looks like after clicking "confligure" in the Event Log upon opening the code directory.: 
![Screenshot 2022-05-03 212036](https://user-images.githubusercontent.com/17030269/166622764-774247f6-a052-4200-a073-d522a81a5277.png)

**Comment by jmacc** [comment]
It may be that the project was not downloaded correctly, download it again
