### ISSUE TITLE
Android Basics: Lemonade app

### ISSUE THREAD

**Issue by Andy-Cuong** [google-developer-training/android-basics-kotlin-lemonade-app#40]
Hello, after downloading and unzipping the file, I cannot even start doing the project because the gradle: build or similar is hogging tons of RAM. Each time I retry and open task manager, there are almost one hundred OpenJDK Platform Binary tasks are running and take up to 95% RAM. Due to this, I keep getting the error like below:

**Unable to start the daemon process.
This problem might be caused by incorrect configuration of the daemon.
For example, an unrecognized jvm option is used.
Please refer to the User Manual chapter on the daemon at https://docs.gradle.org/6.5/userguide/gradle_daemon.html
Process command line: D:\Program Files (D drive)\Android\Android Studio\jre\bin\java.exe --add-opens java.base/java.util=ALL-UNNAMED --add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/java.lang.invoke=ALL-UNNAMED --add-opens java.prefs/java.util.prefs=ALL-UNNAMED -Xmx1024m -Dfile.encoding=UTF-8 -Duser.country=US -Duser.language=en -Duser.variant -cp C:\Users\nguye\.gradle\wrapper\dists\gradle-6.5-bin\6nifqtx7604sqp1q6g8wikw7p\gradle-6.5\lib\gradle-launcher-6.5.jar org.gradle.launcher.daemon.bootstrap.GradleDaemon 6.5
Please read the following process output to find out more:
-----------------------
#
# There is insufficient memory for the Java Runtime Environment to continue.
# Native memory allocation (malloc) failed to allocate 39536 bytes for Chunk::new
# An error report file with more information is saved as:
# C:\Users\myName\.gradle\daemon\6.5\hs_err_pid5432.log
#
# Compiler replay data is saved as:
# C:\Users\myName\.gradle\daemon\6.5\replay_pid5432.log

-----------------------
Check the JVM arguments defined for the gradle process in:
 - gradle.properties in project root directory**

My laptop has 8GB RAM and still runs out of RAM in no time, how strong is my device supposed to be to run this project????

**Comment by jmacc** [comment]
I generate a degree problem, reinstall or update your android studio

**Comment by Andy-Cuong** [comment]
Thank you, I have been able to fixed this issue. Apparently the project-level and app-level gradle.build file are considerably out-of-date. So is the gradle-wrapper.properties. I updated those files using VSCode and the project run as expected.
