### ISSUE TITLE
Android Basics: Lemonade app

### ISSUE THREAD

**Issue by sawyerhamann** [google-developer-training/android-basics-kotlin-lemonade-app#48]
**URL of codelab**

https://developer.android.com/codelabs/basic-android-kotlin-training-project-lemonade?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-four%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-project-lemonade#6

**In which task and step of the codelab can this issue be found?**

Step 7: Testing Instructions

**Describe the problem**

The test: `test_picking_lemon_proceeds_to_squeeze_state` provided in the project for the lemonade project will fail if the student correctly implements the `setViewElements()` method using string resource: `lemon_squeeze` along with the `squeezeCount` variable to update the string resource with the number of squeezes so far:
`textAction.text = resources.getString(R.string.lemon_squeeze, squeezeCount)` 

However, the test will pass with the code `textAction.setText(R.string.lemon_squeeze)` which will not correctly display the updated squeeze count in the text view.

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 2021.2.1 | Chipmunk
_API version of the emulator:_ 31

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

<img width="1552" alt="Screen Shot 2022-08-29 at 12 01 07 PM" src="https://user-images.githubusercontent.com/3834879/187114730-6237f09b-826f-4e05-b9d6-ae941d90aa26.png">
<img width="1552" alt="Screen Shot 2022-08-29 at 12 02 32 PM" src="https://user-images.githubusercontent.com/3834879/187114742-e53981e8-79b4-4b88-aed1-f7b4af5f1482.png">

**Comment by mostafaSamir33** [comment]
excuse me can you send me your project lemonade app because i can't transition between states although i did every thing, i did the test also but still don't know the solution
