### ISSUE TITLE
Android Basics: Lemonade app tests not working in Studio Electric Eel

### ISSUE THREAD

**Issue by christate** [google-developer-training/android-basics-kotlin-lemonade-app#61]
I've downloaded the Lemonade sample app for https://developer.android.com/codelabs/basic-android-kotlin-training-project-lemonade and am checking the codelabs in that module.  The final section, "Testing instructions," is comprehensively failing in an unexpected way:

> `android.content.ActivityNotFoundException`: Unable to find explicit activity class `{com.example.lemonade.test/androidx.test.core.app.InstrumentationActivityInvoker$BootstrapActivity}`; have you declared this activity in your `AndroidManifest.xml`, or does your intent not match its declared `<intent-filter>`?

I'm guessing this is a project configuration error, missing AndroidX libraries or something similar?  The whole project is presented as download-then-import, so perhaps the downloadable project is out of date now with respect to the current release version of Android Studio?

**Comment by Caitiff5** [comment]
Just had the same Issue: #62 Worked again after upgrading dependency "androidx.test:core-ktx:1.4.0" to "androidx.test:core-ktx:1.5.0"
