### ISSUE TITLE
(Android Basics: Lemonade app): Can't work with the practice file for Kotlin

### ISSUE THREAD

**Issue by JustTheK** [google-developer-training/android-basics-kotlin-lemonade-app#65]
![image](https://user-images.githubusercontent.com/125382925/218781747-3819c0ca-64a9-493d-ba23-a7fa77121bfc.png)

Don't know why. until now, every file that I downloades worked fine, except this. Can't run, can't design, don't know what to do

**Comment by Tibor42** [comment]
look at issue #60 and make sure you use the correct path..

happy hacking :-)
